### PR TITLE
Added MANIFEST file, so "make dist" will work

### PR DESCRIPTION
**Pull request by neilb**
Hi Dave,

With this PR applied, you can then run:

    perl Makefile.PL
    make dist

And that will result in a tarball which includes both a META.yml and META.json. That will make life easier for a good number of tools. And will also mean that Expect will contribute to the CPAN River calculations, as code will be able to tie Expect to the dists that it relies on.

Best to make sure you've got the latest version of ExtUtils::MakeMaker installed first.

Also, I recommend that you rename the repo name to "Expect" rather than "expect.pm". This is the convention for CPAN dists on github. At first I couldn't find this repo, because I was looking for a repo called "Expect". But then I found you on github, and thus the "expect.pm".

Having renamed the repo, you should then update Makefile.PL, so the repository metadata refers to your repo, and not Gabor's.

Let me know if I can help in any way.

Cheers,
Neil

### CODE REVIEW

**Comment by neilb** [comment]
I should have also said:

> I bumped the version number ready for a release, and put that in Changes.
> You'll need to set the date when you release in the Changes file.

**Comment by jacoby** [comment]
Thanks.

**Comment by jacoby** [comment]
I see MYMETA.yml exports:
    author:
      - unknown

Found the point explaining AUTHOR in https://metacpan.org/release/ExtUtils-MakeMaker but not where/how it's set.

**Comment by jacoby** [comment]
Or, is this a thing not to worry about?

**Pull request merged**
